services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: api.Dockerfile
      tags:
        - api
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules/
    deploy:
      resources:
        limits:
          memory: 2000M
