services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: api.Dockerfile
      tags:
        - api
    ports:
      - '${PORT}:${PORT}'
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules/
    deploy:
      resources:
        limits:
          memory: 2000M
